### ISSUE TITLE
Convert to Docker multi-stage builds

### ISSUE THREAD

**Issue by 0xdevalias** [jumanjihouse/docker-ssllabs-scan#54]
With multi-stage builds in the latest Docker tooling, the build workflow of this can be simplified right down. If I were to work on a PR for it, would you be interested in merging?

**Comment by jumanjiman** [comment]
short answer: absolutely yes

longer answer: i'm keen to move to multi-stage builds, but my local dev builders are on coreos stable.
therefore i've been watching for stable to update past its current docker version 1.12.6

in my current setup, i think this would require two commits:

* 1 against https://github.com/jumanjihouse/cci/blob/master/src/Dockerfile to update to docker 17.0.6
* 1 to this repo for multi-stage build

**Comment by jumanjiman** [comment]
Hi @0xdevalias 

CoreOS has made docker ce 17.07.0 available as of
https://coreos.com/blog/toward-docker-17-in-container-linux
so I've upgraded my local builders.

With that out of the way, I've also converted to multi-stage build via https://github.com/jumanjihouse/docker-ssllabs-scan/pull/56.

**Comment by 0xdevalias** [comment]
Great to hear! Thanks :)
