### ISSUE TITLE
Unable to resolve domain name

### ISSUE THREAD

**Issue by jamiejackson** [jumanjihouse/docker-ssllabs-scan#64]
I don't understand the peculiarities of this image. I'm trying to run it on a local site, which is defined in `/etc/hosts`.

Regular containers resolve the domain fine:

```
$ docker run --rm  alpine ash -c 'apk update && apk add curl && curl --insecure -I https://local2.hudexchange.info'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
v3.7.0-270-g50b32074fd [http://dl-cdn.alpinelinux.org/alpine/v3.7/main]
v3.7.0-265-g734499ca93 [http://dl-cdn.alpinelinux.org/alpine/v3.7/community]
OK: 9054 distinct packages available
(1/4) Installing ca-certificates (20171114-r0)
(2/4) Installing libssh2 (1.8.0-r2)
(3/4) Installing libcurl (7.61.0-r0)
(4/4) Installing curl (7.61.0-r0)
Executing busybox-1.27.2-r7.trigger
Executing ca-certificates-20171114-r0.trigger
OK: 6 MiB in 15 packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 32566    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx/1.14.0
Date: Wed, 12 Sep 2018 02:54:55 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 32566
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=3600; includeSubdomains;
Strict-Transport-Security: max-age=1200
Generator: Mura CMS 7.0
Content-Language: en-US
Set-Cookie: cfid=63a0743e-562e-41fb-aa0a-98a6fed4a3e8;Path=/;Expires=Tue, 02-Oct-2018 04:32:58 UTC;HTTPOnly
Set-Cookie: cftoken=0;Path=/;Expires=Tue, 02-Oct-2018 04:32:58 UTC;HTTPOnly
Set-Cookie: MXP_TRACKINGID=2E22A2D4-1D85-4928-A84FF1C1B5AFFF33;Path=/;Expires=Thu, 10-Sep-2048 10:46:24 UTC;Secure;HTTPOnly
Set-Cookie: mobileFormat=false;Path=/;Expires=Thu, 10-Sep-2048 10:46:24 UTC;Secure;HTTPOnly
SET-COOKIE: cfid=63a0743e-562e-41fb-aa0a-98a6fed4a3e8;path=/;secure;HttpOnly;
SET-COOKIE: cftoken=0;path=/;secure;HttpOnly;
Vary: Origin
Strict-Transport-Security: max-age=31536000
```

This one fails:

```
$ docker run --read-only --cap-drop all --rm -it jumanjiman/ssllabs-scan:latest -grade -usecache -insecure https://local2.hudexchange.info
2018/09/12 02:55:03 [INFO] SSL Labs v1.32.5 (criteria version 2009p)
2018/09/12 02:55:03 [NOTICE] Server message: This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://www.ssllabs.com/about/terms.html
2018/09/12 02:55:05 [INFO] Assessment starting: https://local2.hudexchange.info
2018/09/12 02:55:06 [WARN] Assessment failed: https://local2.hudexchange.info (Unable to resolve domain name)

2018/09/12 02:55:06 [INFO] All assessments complete; shutting down
```

What's the scoop?

**Comment by jumanjiman** [comment]
Hi @jamiejackson 

Thank you for reporting this.

In your example of "regular containers", the container includes the standard libc stub resolver and `/etc/nsswitch.conf`. Therefore entries in `/etc/hosts` are honored.

My container is built "from scratch", so it does not have libc.
Instead, it uses the golang `net` resolver.

While reading up on the golang resolver, I learned that it uses `/etc/nsswitch.conf` if the file exists.
I've opened https://github.com/jumanjihouse/docker-ssllabs-scan/pull/65 to add `/etc/nsswitch.conf` along with a test to show that `/etc/hosts` entries are used.

That's the good news.

The caveat is that this scanner is only a client to the [Qualys SSL Labs service](https://www.ssllabs.com/ssltest/). If the hosted service cannot resolve your hostname, it cannot scan your server. If the hosted service cannot reach your server, it cannot perform the scan.

For internal sites, I use https://github.com/jumanjihouse/docker-testssl to perform scans.

**Comment by jamiejackson** [comment]
Thanks for the explanation @jumanjiman; great info. I hadn't realized that the underlying tool wasn't an offline scanner.

However, based on the info you provided, does it even make sense for this container to honor custom `/etc/hosts` entries? It would seem that since the ssllabs API is going to use real DNS, anyway, having the container recognize `/etc/hosts` wouldn't be helpful.

I'll also check out the the internal tool you mentioned.

**Comment by jumanjiman** [comment]
> does it even make sense for this container to honor custom `/etc/hosts` entries?

Not really.

But from the perspective of "correctness", I think it does make sense.
I have several "from scratch" containers that include static golang binaries, so I'm now planning to add `/etc/nsswitch.conf` to each of them.

Plus the PR adds useful clarifications to the README.

**Comment by aardbol** [comment]
I also have an issue with "Unable to resolve domain name" for public accessible URLs. The resolving inside the container works flawless but this tool experiences this issue for some reason. I can get it to work by using the `-usechache` flag, although that doesn't solve the resolve issue itself.
