### ISSUE TITLE
Update ssllabs-scan

### ISSUE THREAD

**Issue by matt-horwood-mayden** [jumanjihouse/docker-ssllabs-scan#67]
Hi, 

I have tried to use your repo to build my own image, but ssllabs-scan command had `v3` on thr end and didnt work with the new 1.4 version.

here is the diff of my changes.
```
index 7242399..3a6dfbd 100644
--- a/scanner/Dockerfile
+++ b/scanner/Dockerfile
@@ -34,7 +34,7 @@ RUN cd /tmp && \
       -tags netgo \
       -ldflags '-extldflags "-static" -s' \
       -buildmode exe \
-      ssllabs-scan-v3.go
+      ssllabs-scan.go
 
 #
 # Build the runtime image.
@@ -46,7 +46,7 @@ ENTRYPOINT ["/ssllabs-scan"]
 CMD ["--help"]
 
 ARG VERSION
-COPY --from=scanner_builder /tmp/ssllabs-scan-${VERSION}/ssllabs-scan-v3 /ssllabs-scan
+COPY --from=scanner_builder /tmp/ssllabs-scan-${VERSION}/ssllabs-scan /ssllabs-scan
 COPY --from=scanner_builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
 COPY . /
```

**Comment by jumanjiman** [comment]
Hi @matt-horwood-mayden 

Sorry i missed the notification of your issue.

> didnt work with the new 1.4 version

The current [upstream version is 1.5](https://github.com/ssllabs/ssllabs-scan/releases/tag/v1.5.0).





> here is the diff of my changes

That's almost the exact opposite of [commit 33555ed5a](https://github.com/jumanjihouse/docker-ssllabs-scan/commit/33555ed5a92f4e50c60e3c4c6226e55388d48252) that updated the image from 1.4 to 1.5!

If you want to build 1.4, you could `git checkout 33555ed5a^`.
