### ISSUE TITLE
Can't get hostfile in container

### ISSUE THREAD

**Issue by AronllStone** [jumanjihouse/docker-ssllabs-scan#80]
Hi,
When I try to use hostfile, sslscan-util can't read it in container
Could you help me with this?

```
root@4834c2cf6b73:/opt/buildagent/work/3e827ec943614e5f# ls -la
drwxr-xr-x. 4 root root   137 Jun  4 08:31 .
drwxrwxr-x. 9  997  993   183 Jun  4 08:31 ..
-rw-r--r--. 1 root root   495 Jun  4 08:31 list.txt
root@4834c2cf6b73:/opt/buildagent/work/3e827ec943614e5f# docker run -v $(pwd):/tmp:ro  jumanjiman/ssllabs-scan -hostfile "/tmp/list.txt"
2020/06/04 08:38:35 [ERROR] Reading from specified hostfile failed: open /tmp/list.txt: no such file or directory
```
It also doesn't work with the next parameter:
`-v "/opt/buildagent/work/3e827ec943614e5f:/tmp:ro"`

Regards Konstantin

**Comment by AronllStone** [comment]
All fine
It's my mistake
I was wrong with containers and running it on Teamcity Agent in Docker.
Command with -v parameter is true

**Comment by jumanjiman** [comment]
cool, thanks for the updates.
